dist: bionic

services:
  - redis

language: python
python:
  - "3.8"

install:
  - pip install -r requirements/local.txt

script:
  - coverage run -m pytest

after_success:
  - "pip install coveralls; coveralls"
